### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by aleave** [SciML/DiffEqDocs.jl#352]
I found two broken links in the documentation:

- under "Example 2: Solving Systems of Equations", link pointing to 
   http://docs.juliadiffeq.org/latest/basics/plot.html#Choosing-Variables-1

- under "ODE Problems" link to "DiffEqProblemLibrary.jl" pointing to
  https://github.com/JuliaDiffEq/DiffEqProblemLibrary.jl/blob/master/src/ode_premade_problems.jl

**Comment by ChrisRackauckas** [comment]
What version of the docs? Is this on dev? I can't find it.

**Comment by aleave** [comment]
I just checked and I realized that Google sent me on an old version doc page (4.6). I do not see the broken links in the most recent version so I would close the issue.

**Comment by ChrisRackauckas** [comment]
No worries. Thanks. Yeah... we need to figure out how to get Google to prefer the stable links.
