### ISSUE TITLE
EnsembleThreads() not working on a new PC

### ISSUE THREAD

**Issue by lfsc507** [SciML/DiffEqDocs.jl#361]
Hello. I tried the following example on 2 PCs:

```
function f(du,u,p,t)
    du[1] = 1.01*u[1]
end
u0 = [0.0, 0.0]
tspan = (0.0,1.0)
prob = ODEProblem(f,u0,tspan)
n = 100

initial_conditions = range(0, stop=1, length=n)
function prob_func(prob,i,repeat)
    prob.u0[1] = initial_conditions[i]
    prob
end
ensemble_prob = EnsembleProblem(prob,prob_func=prob_func)
sim_1 = solve(ensemble_prob,Tsit5()
            ,EnsembleThreads(),
            trajectories=100)
sim_2 = solve(ensemble_prob,Tsit5()
            ,EnsembleDistributed(),
            trajectories=100)
ss_sol_1 = hcat(collect(EnsembleAnalysis.get_timepoint(sim_1,0))...);
ss_sol_2 = hcat(collect(EnsembleAnalysis.get_timepoint(sim_2,0))...);
plot(1:n, ss_sol_1[1,:], label="x_t0 EnsembleThreads")
plot!(1:n, ss_sol_2[1,:], label="x_t0 EnsembleDistributed")
```
On PC1 (E5-1650, Ubuntu 18.04, Julia 1.4.1), the solutions look fine: each simulation gets anticipated initial condition.
On PC2 (i9-9900K, Ubuntu 20.04, Julia 1.4.1), where I got EnsembleGPUArray() working, EnsembleThreads() produced a strange behavior: simulations get unexpected initial conditions shown below. 

![ens](https://user-images.githubusercontent.com/41975604/82719562-e1b60600-9c79-11ea-8e4a-55750af48f59.png)

EnsembleDistributed() works fine, but it's slower than EnsembleThreads() on PC1 with my ode problem.

**Comment by ChrisRackauckas** [comment]
It's a thread-safety issue causing the ordering to be wrong. https://github.com/SciML/DiffEqBase.jl/pull/518 is the fix.

**Comment by lfsc507** [comment]
Thanks!

Will this fix the issue that if I scan a parameter with multiple simulations, the parameter values "leak" from one trajectory to another during simulations? I thought it's the same problem, but just want to make sure this is the ordering problem you mentioned. This is again not a problem with PC1 or EnsembleDistributed()

```
using Pkg
using Plots
using DifferentialEquations

function f(du,u,p,t)
    du[1] = p[1] - u[1]
end
u0 = [0.0]
p = [0.0]
tspan = (0.0,100.0)
prob = ODEProblem(f,u0,tspan, p)
n = 10

pars = range(0, stop=100, length=n)
function prob_func(prob,i,repeat)
    prob.p[1] = pars[i]
    prob
end
ensemble_prob = EnsembleProblem(prob,prob_func=prob_func)
sim_1 = solve(ensemble_prob,Tsit5()
            ,EnsembleThreads(),
            trajectories=n)
sim_2 = solve(ensemble_prob,Tsit5()
            ,EnsembleDistributed(),
            trajectories=n)
p1 = plot(sim_1,linealpha=0.8, title="EnsembleThreads")
p2 = plot(sim_2,linealpha=0.8, title="EnsembleDistributed")
plot(p1, p2, layout=2)
```
![ens](https://user-images.githubusercontent.com/41975604/82732912-68043380-9cde-11ea-9a16-85533d6430f9.png)

**Comment by ChrisRackauckas** [comment]
Yup, that was another thread-safety issue:

![threads](https://user-images.githubusercontent.com/1814174/82733087-7d2d9200-9cdf-11ea-8f9b-29c971aa760b.png)

**Comment by ChrisRackauckas** [comment]
I'll get this patch released in an hour.

**Comment by lfsc507** [comment]
Awesome. Thanks!
