### ISSUE TITLE
Link to MonteCarlo page for EnsembleSimulations tutorial

### ISSUE THREAD

**Issue by metanoid** [SciML/DiffEqDocs.jl#363]
On this page: [Ensemble Simulations](docs.sciml.ai/dev/tutorials/sde_example/#Ensemble-Simulations-1)

There is the following:

> Many more controls are defined at the Monte Carlo page, including analysis tools.

Monte Carlo page should be a link, I think, but I can't find the page it should be linking to.

**Comment by ChrisRackauckas** [comment]
Monte Carlo simulations was renamed to Ensemble simulations sometime about a year ago, so that should get cleaned up in the docs.

**Comment by ChrisRackauckas** [comment]
What page is this? I don't see it in https://docs.sciml.ai/latest/

**Comment by metanoid** [comment]
Apologies, I screwed up the link.

[https://docs.sciml.ai/latest/tutorials/sde_example/#Ensemble-Simulations-1](https://docs.sciml.ai/latest/tutorials/sde_example/#Ensemble-Simulations-1)

**Comment by ChrisRackauckas** [comment]
Awesome, updated in https://github.com/SciML/DiffEqDocs.jl/blob/master/docs/src/tutorials/sde_example.md
