### ISSUE TITLE
Misspelling "_prob" in the tutorial of Local Sensitivity Analysis

### ISSUE THREAD

**Issue by stevengogogo** [SciML/DiffEqDocs.jl#374]
I found a possible misspelling error in https://docs.sciml.ai/v6.12/analysis/sensitivity/#solve-Differentiation-Examples-1

## The original code on documentation
```julia
function sum_of_solution(u0,p)
  _prob = remake(prob,u0=u0,p=p)
  sum(solve(prob,Tsit5(),saveat=0.1,sensealg=QuadratureAdjoint()))
end
du01,dp1 = Zygote.gradient(sum_of_solution,u0,p)
```
Notice that the  `sum(solve(prob,Tsit5(),saveat=0.1,sensealg=QuadratureAdjoint()))` should be `sum(solve(_prob,Tsit5(),saveat=0.1,sensealg=QuadratureAdjoint()))` with modified _prob.

**Comment by ChrisRackauckas** [comment]
Looks like it's fixed on the current docs https://docs.sciml.ai/dev/analysis/sensitivity/
