### ISSUE TITLE
ODELocalSensitivityProblem

### ISSUE THREAD

**Issue by pkpddude** [SciML/DiffEqDocs.jl#401]
This does not see to work anymore.  I assume there is an update.  i get the following error

UndefVarError: ODELocalSensitivityProblem not defined

**Comment by ChrisRackauckas** [comment]
It's `ODEForwardSensitivityProblem`. https://diffeq.sciml.ai/stable/analysis/sensitivity/ . You must've been looking at the old docs, though I see the titles are a few years old too so I fixed that now. Thanks!

**Comment by pkpddude** [comment]
Also, I forgot to install the DifferentialSensitivity library as I recently reinstalled the JuliaPro version to access Pumas.AI.

Thanks for the prompt reply

Robert D. Johnson, Ph.D
[cid:image001.png@01D675F3.FBA007C0]
Procter & Gamble
Mason Business Center
8700 Mason Montgomery Road
johnson.rd.1@pg.com<mailto:johnson.rd.1@pg.com>
(513) 634-9827

COVID19:
I wish it need not have happened in my time and
So do all who live to see such times.
All we have to decide is what to do with the time that is given us

**Comment by ChrisRackauckas** [comment]
Oh got it.
