### ISSUE TITLE
Correct DAEFunction parameters

### ISSUE THREAD

**Issue by dangirsh** [SciML/DiffEqDocs.jl#405]
I assume the `DAEFunction` parameters in the default constructor shown [here](https://github.com/SciML/DiffEqDocs.jl/blob/ccf16708a78fbdf65c512d3b449ac498f434a077/docs/src/features/performance_overloads.md#daefunction) should match the parameters in the DAEFunction struct [here](https://github.com/SciML/DiffEqBase.jl/blob/50fe37da2c1f60b213236de81cbb3adb65ad000c/src/diffeqfunction.jl#L203).

I was bitten by this because a `mass_matrix` parameter is listed in the docs, but doesn't exist in the code.

**Comment by ChrisRackauckas** [comment]
Fixed. Yeah, mass matrices don't make sense with DAEs.

**Comment by ChrisRackauckas** [comment]
well, fully-implicit DAE descriptions at least.

**Comment by dangirsh** [comment]
Makes sense, thanks!
