### ISSUE TITLE
Missing footnote on non-autonomous solvers page

### ISSUE THREAD

**Issue by imciner2** [SciML/DiffEqDocs.jl#424]
The footnote associated with the `iop` option of the exponential method is missing.

**Comment by ChrisRackauckas** [comment]
Which footnote?

**Comment by imciner2** [comment]
On https://diffeq.sciml.ai/stable/solvers/nonautonomous_linear_ode/, there is a footnote on the `iop` option here https://diffeq.sciml.ai/stable/solvers/nonautonomous_linear_ode/#Exponential-Methods-for-Linear-and-Affine-Problems. That footnote link doesn't go anywhere.

**Comment by ChrisRackauckas** [comment]
I think it should point to https://www.sciencedirect.com/science/article/pii/S0021999118304042
