### ISSUE TITLE
Typo in SDE tutorial example?

### ISSUE THREAD

**Issue by zenkavi** [SciML/DiffEqDocs.jl#431]
Hi,
I plan to send a PR fixing some typos in the tutorials (which are extremely helpful, thank you!) but I wanted to check on something that wasn't clear to me whether it was a typo or intentional.

In the definition of the noise function in [example 4 of the SDE tutorial example](https://diffeq.sciml.ai/v6.0/tutorials/sde_example.html#Example-4:-Systems-of-SDEs-with-Non-Diagonal-Noise-1) is the code supposed to be:

```
du[1,4] = 0.12u[2]
du[2,1] = 1.2u[1]
```
or is this is a typo and it should have been: 
```
du[1,4] = 0.12u[1]
du[2,1] = 1.2u[2]
```

**Comment by ChrisRackauckas** [comment]
yes, that looks like a typo. Nice find!
