### ISSUE TITLE
Typo/unclear sentence in stiff ODE solver recommendations 

### ISSUE THREAD

**Issue by dnadlinger** [SciML/DiffEqDocs.jl#435]
docs/src/solvers/ode_solve.md says: "For stiff problems at high tolerances (>1e-2?) it is recommended that you use Rosenbrock23 or TRBDF2. These are robust to oscillations and massive stiffness is needed, though are only efficient when low accuracy is needed."

What is "These are robust to oscillations and massive stiffness is needed" supposed to mean?

**Comment by ChrisRackauckas** [comment]
"These are robust to oscillations and massive stiffness, though ..."

It has to do with stability. Those methods are the low order L-stable and higher B-stability with stiffly-accurate tableau methods. Rosenbrock23 is a W-method. Compare that to BDFs like CVODE which isn't even A-stable, and there are some cases where you can show they straight up fail while these higher stability methods work.

**Comment by dnadlinger** [comment]
Thanks for the clarification!
