### ISSUE TITLE
Solving Systems of ODE crashes

### ISSUE THREAD

**Issue by houchmandzadeh** [SciML/DiffEqDocs.jl#437]
Julia version : 1.4.1
DifferentialEquations version : v6.16.0
OS : Ubuntu 20.04.02 LTS

## Problem description : 
DifferentialEquations works fine when used for scalar problems. But I cannot solve the most basic systems of ODE. Even the example given in tutorial (see below) crashes. There is no error message, only a general message "The Kernel has died and will restart automatically". I have tried to change various parameters, reducing time span, ... to no avail.

### Example of the tutorial : 
function lorenz!(du,u,p,t)
   du[1] = 10.0*(u[2]-u[1])
   du[2] = u[1]*(28.0-u[3]) - u[2]
   du[3] = u[1]*u[2] - (8/3)*u[3]
end
u0 = [1.0;0.0;0.0]
tspan = (0.0,100.0)
prob = ODEProblem(lorenz!,u0,tspan)
sol = solve(prob)

**Comment by ChrisRackauckas** [comment]
Is this an issue with the standard Julia v1.5 binary downloaded from https://julialang.org/downloads/ ?

**Comment by ChrisRackauckas** [comment]
Not reproducible and the tests are all passing on anything v1.6+, so this at least doesn't exist anymore.
