### ISSUE TITLE
`dense` description in Common Solver Options

### ISSUE THREAD

**Issue by zmoon** [SciML/DiffEqDocs.jl#443]
[Here](https://github.com/SciML/DiffEqDocs.jl/blame/master/docs/src/basics/common_solver_opts.md#L48) it says `save_everystep && !isempty(saveat)` is the default. But from [the relevant code](https://github.com/SciML/OrdinaryDiffEq.jl/blob/64845c4b304508ce178e57a78066487a9ef54ef6/src/solve.jl#L24) (and my experience trying it out) that does not appear to be the case. It seems that it should instead say `save_everystep && isempty(saveat)` in the docs.

**Comment by ChrisRackauckas** [comment]
oh yes, that's a typo.

**Comment by ChrisRackauckas** [comment]
This got fixed in the docstring https://github.com/SciML/DiffEqBase.jl/blob/master/src/solve.jl
