### ISSUE TITLE
Problem with Delay Differential Equations

### ISSUE THREAD

**Issue by ChrisNabold** [SciML/DiffEqDocs.jl#444]
I tried to convert an Example from R (input below EX8.7
[EX8.7r.txt](https://github.com/SciML/DiffEqDocs.jl/files/6082017/EX8.7r.txt)
[EX8.7.txt](https://github.com/SciML/DiffEqDocs.jl/files/6082021/EX8.7.txt)

r) which works fine. I converted it to Julia (EX8.7.txt) but I receive an error executing it on Julia:. Can anybody help me to find my error - thank you

               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.3 (2020-11-09)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using DifferentialEquations, Plots

julia> function func(du,u,h,p,t)
       tau = p
       tlag = t - tau
       hist = h(p, t - tau)[1]
       du[1] = r*u[1]*(1.0 -hist)
       end
func (generic function with 1 method)

julia> h(p, t) = [1.0]
h (generic function with 1 method)

julia> tau = 1.0
1.0

julia> lags = [tau]
1-element Array{Float64,1}:
 1.0

julia> r = 1.0; K = 1.0
1.0

julia> p = (r, K, tau)
(1.0, 1.0, 1.0)

julia> tspan = (0.0, 100.0)
(0.0, 100.0)

julia> u0 = [0.0]
1-element Array{Float64,1}:
 0.0

julia> prob = DDEProblem(func,u0,h,tspan,p; constant_lags=lags)
DDEProblem with uType Array{Float64,1} and tType Float64. In-place: true
timespan: (0.0, 100.0)
u0: [0.0]

julia> alg = MethodOfSteps(Tsit5())
MethodOfSteps{Tsit5,NLFunctional{Rational{Int64},Rational{Int64}},false}(Tsit5(), NLFunctional{Rational{Int64},Rational{Int64}}(1//100, 1//5, 10))

julia> sol = solve(prob,alg)
ERROR: MethodError: no method matching -(::Float64, ::Tuple{Float64,Float64,Float64})
Closest candidates are:
  -(::ChainRulesCore.DoesNotExist, ::Any) at C:\Users\Chris\.julia\packages\ChainRulesCore\7d1hl\src\differential_arithmetic.jl:25
  -(::Float64, ::Float64) at float.jl:403
  -(::Float64) at float.jl:393
  ...
Stacktrace:

**Comment by ChrisRackauckas** [comment]
`tau = p` doesn't make sense: you defined it as `tau = p[3]` when you did `p = (r, K, tau)`

**Comment by ChrisNabold** [comment]
I am still trying to solve the problem. Where is the eror? 
[EX8.7a.txt](https://github.com/SciML/DiffEqDocs.jl/files/6102200/EX8.7a.txt)

julia> using DifferentialEquations, Plots

julia> const r = 1.0; const K = 1.0, const tau = 1.0
(1.0, 1.0)

julia> function func(t,u,h,du)
       du = r*u*h(t-tau)K
       end
func (generic function with 1 method)

julia> lags = tau
1.0

julia> h(t) = 1.0
h (generic function with 1 method)

julia> tspan = (0.0, 100.0)
(0.0, 100.0)

julia> u0 = 0.0
0.0

julia> p = tau
1.0

julia> prob = DDEProblem(func,u0,h,tspan; constant_lags=lags)
DDEProblem with uType Float64 and tType Float64. In-place: false
timespan: (0.0, 100.0)
u0: 0.0

julia> alg = MethodOfSteps(Tsit5())
MethodOfSteps{Tsit5,NLFunctional{Rational{Int64},Rational{Int64}},false}(Tsit5(), NLFunctional{Rational{Int64},Rational{Int64}}(1//100, 1//5, 10))

julia> sol = solve(prob,alg)
ERROR: MethodError: objects of type SciMLBase.NullParameters are not callable
Stacktrace:
 [1] func(::Float64, ::Function, ::SciMLBase.NullParameters, ::Float64) at .\REPL[3]:2
