### ISSUE TITLE
Delay Differential Equations Undevined ConstantLagDDF

### ISSUE THREAD

**Issue by ChrisNabold** [SciML/DiffEqDocs.jl#446]
_
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.3 (2020-11-09)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> using DifferentialEquations, Plots

julia> const p0 = 0.2; const q0 = 0.3; const v0 = 1; const d0 = 5
5

julia> const p1 = 0.2; const q1 = 0.3; const v1 = 1; const d1 = 1
1

julia> const d2 = 1; const beta0 = 1; const beta1 = 1; const tau = 1
1

julia> function bc_model(t,u,h,du)
         du[1] = (v0/(1+beta0*(h(t-tau)[3]^2))) * (p0 - q0)*u[1] - d0*u[1]
         du[2] = (v0/(1+beta0*(h(t-tau)[3]^2))) * (1 - p0 + q0)*u[1] +
                 (v1/(1+beta1*(h(t-tau)[3]^2))) * (p1 - q1)*u[2] - d1*u[2]
         du[3] = (v1/(1+beta1*(h(t-tau)[3]^2))) * (1 - p1 + q1)*u[2] - d2*u[3]
       end
bc_model (generic function with 1 method)

julia> lags = [tau]
1-element Array{Int64,1}:
 1

julia> h(t) = ones(3)
h (generic function with 1 method)

julia> tspan = (0.0,10.0)
(0.0, 10.0)

julia> u0 = [1.0,1.0,1.0]
3-element Array{Float64,1}:
 1.0
 1.0
 1.0

julia> prob = ConstantLagDDEProblem(bc_model,h,u0,lags,tspan)
ERROR: UndefVarError: ConstantLagDDEProblem not defined
Stacktrace:
 [1] top-level scope at REPL[10]:1

**Comment by ChrisRackauckas** [comment]
You're looking at really old documentation. See the latest documentation: https://diffeq.sciml.ai/stable/

**Comment by ChrisRackauckas** [comment]
I added a new banner to alert people to old docs.
