### ISSUE TITLE
Ordering of the arguments q and p in HamiltonianProblem

### ISSUE THREAD

**Issue by hurak** [SciML/DiffEqDocs.jl#451]
The documentation seems inconsistent with as for the ordering of `q` and `p` in the definition of `HamiltonianProblem` at [https://diffeq.sciml.ai/stable/types/dynamical_types/#Constructors-2](https://diffeq.sciml.ai/stable/types/dynamical_types/#Constructors-2). It is first stated that Hamiltonian has a general form ``H(q,p)`` and then it is written that the constructor for `HamiltonianProblem` is 
```julia
HamiltonianProblem{T}(H,p0,q0,tspan;kwargs...)
```
Isn't the latter a typo? I mean, shouldn't it be
```julia
HamiltonianProblem{T}(H,q0,p0,tspan;kwargs...)
```
?

**Comment by ChrisRackauckas** [comment]
Yes, quite possibly a typo.

**Comment by BarrOff** [comment]
Hello,

looking at the [source code](https://github.com/SciML/DiffEqPhysics.jl/blob/master/src/hamiltonian.jl), the constructor at the [location mentioned above](https://diffeq.sciml.ai/stable/types/dynamical_types/#Constructors-2) is correct. The general form should be `H(p, q)`

There also seems to be a typo in the commit for DynamicalODEProblem [here](https://github.com/SciML/SciMLBase.jl/blob/master/src/problems/ode_problems.jl) at the lines 88/89. f1 and f2 should be switched there.

**Comment by ChrisRackauckas** [comment]
Thanks!
