### ISSUE TITLE
wrong solution of a simple linear ODE

### ISSUE THREAD

**Issue by lampretl** [SciML/DiffEqDocs.jl#479]
Forgive me for asking a seemingly simple question, but why does the following code produce two distinct solutions? 
```
using Plots, DifferentialEquations
f(u,p,t)=-2t*u+t^3; u0=1.0; tspan=(-3.0,3.0); 
prb= ODEProblem(f,u0,tspan);   
sol= solve(prb, reltol=1e-8, abstol=1e-8); 
plot(sol,linewidth=5,title="linear 1D ODE",xaxis="t",yaxis="u(t)",label="numerical solution") 
plot!(sol.t, t->0.5*(3*exp(-t^2)+t^2-1), lw=3,ls=:dash,label="exact solution")
```
Btw, this is the first example from https://diffeq.sciml.ai/stable/tutorials/ode_example/ but slightly edited. (I solved the ODE symbolically using Mathematica)

**Comment by ChrisRackauckas** [comment]
Looking at the analytical solution, you had a sign error. An easy way to see that the analytical solution is incorrect is just that `f(-3) != 1, i.e. your analytical solution doesn't even satisfy the initial condition.

Using Wolfram Alpha: https://www.wolframalpha.com/input/?i=u%27+%3D+-2t*u%2Bt%5E3%2C+u%28-3%29+%3D+1, typing that in gives you something that directly matches the ODE's output.

```julia
using Plots, DifferentialEquations
f(u,p,t)=-2t*u+t^3; u0=1.0; tspan=(-3.0,3.0);
prb= ODEProblem(f,u0,tspan);
sol= solve(prb, reltol=1e-8, abstol=1e-8);
plot(sol,linewidth=5,title="linear 1D ODE",xaxis="t",yaxis="u(t)",label="numerical solution")
plot(sol.t, t->0.5*(-6*exp(9 - t^2)+t^2-1), lw=3,ls=:dash,label="exact solution")
```

Hopefully that helps.

**Comment by lampretl** [comment]
Aaah, I thought that u0=u(0), not u0=u(-3), the left endpoint of the interval. That explains a lot, thank you!

**Comment by ChrisRackauckas** [comment]
yeah it's whatever the initial condition is. We just refer to it as u0 to give it a name, but of course it could be different in other codes.
