### ISSUE TITLE
Old name/link of the tutorial package still used in the IJulia notebook tutorials section (frontpage)

### ISSUE THREAD

**Issue by evertrol** [SciML/DiffEqDocs.jl#483]
I noticed the name DiffEqTutorials.jl and link https://github.com/SciML/DiffEqTutorials.jl are (still) used at https://diffeq.sciml.ai/dev/#IJulia-Notebook-Tutorials .

The link is forwarded to https://github.com/SciML/SciMLTutorials.jl by GitHub, but the tutorial package installation code in that section doesn't work anymore: `DiffEqTutorials` should probably by replaced by `SciMLTutorials` (that made it work for me):

```
using Pkg
pkg"add https://github.com/SciML/SciMLTutorials.jl"
using SciMLTutorials
SciMLTutorials.open_notebooks()
```

**Comment by ChrisRackauckas** [comment]
Oh haha, yeah that should get updated.
