### ISSUE TITLE
N Body problem example

### ISSUE THREAD

**Issue by forestavros** [SciML/DiffEqDocs.jl#505]
N Body problem example at
https://diffeq.sciml.ai/stable/models/physical/#Example 

displays the following message:

ERROR: LoadError: UndefVarError: NBodyProblem not defined

**Comment by ChrisRackauckas** [comment]
Did you do `using NBodySimulator` like the example shows?

**Comment by forestavros** [comment]
NBodyProblem does not seems to be a method recognized by NBodySimulator.

**Comment by ChrisRackauckas** [comment]
Moved to a separate docs so it stays updated.
