### ISSUE TITLE
Documentation: expression for SDE with jumps

### ISSUE THREAD

**Issue by tom-plaa** [SciML/DiffEqDocs.jl#509]
On the Jump Diffusions tutorial at
DiffEqDocs.jl/docs/src/tutorials/jump_diffusion.md

EDIT: Also seems to be the same in docs/src/types/jump_types.md

I find it confusing to read
```math
\frac{du}{dt} = f(u,p,t) + Σgᵢ(u,t)dWⁱ + Σ h_i(u,p,t)N_i(t)
```

Because it implies \int{ g_i(u,t) dW_i(t) dt} on the diffusion term
And \int{ h_i(u,t) N(t) dt} on the jump term.

I would suggest to adopt the notation used in the Itô diffusions tutorial, something akin to:

```math
du = f(u,p,t)dt + Σgᵢ(u,p,t)dWⁱ(t) + Σ h_i(u,p,t)dNⁱ(t)
```
Because now it implies the expected integrals \int{ g_i(u,p,t) dW_i(t)} and \int{ h_i(u,p,t) dN_i(t)}

By the way, I am assuming that these are the types on integrals being defined by the Problem interface for Jumps, I may be wrong (if so, can you please clarify how they are being defined?).

I assume that having du/dt on the left might have been influenced by the ODE methodology as trying to make it easier to associate with the actual code that one has to write for the integrand functions, but I think this merit might not be worth the confusion that arises regarding how the module is integrating with respect to jump processes.

Thanks for this module, very impressive work!

**Comment by ChrisRackauckas** [comment]
Yes, your proposed changes would be an improvement. Please submit a PR. Thanks!

**Comment by tom-plaa** [comment]
I will do so as soon as I can, thanks!
