### ISSUE TITLE
Link to developer documentation in Overview is broken

### ISSUE THREAD

**Issue by youainti** [SciML/DiffEqDocs.jl#513]
While reading through the documentation [here (lines 89 and 94)](https://github.com/SciML/DiffEqDocs.jl/blob/master/docs/src/basics/overview.md), I found that the link to the developer documentation is broken. I've tried to locate the appropriate website but have been unsucessful.

I just wanted to raise the issue so that someone with a little more information as to where such documentation may have moved to can fix it, or point me in the right direction so that I can fix it.

**Comment by youainti** [comment]
I just found the new link [https://devdocs.sciml.ai/dev/](https://devdocs.sciml.ai/dev/). Are there any contribution details I need to be aware of before submitting corrections?

**Comment by ChrisRackauckas** [comment]
Nope, it's all MIT licensed etc. so a PR would be perfect. Thanks for finding this.
