### ISSUE TITLE
Typo in continous adjoint example?

### ISSUE THREAD

**Issue by DrVogt** [SciML/DiffEqDocs.jl#530]
Howdy,

Here: https://diffeq.sciml.ai/stable/analysis/sensitivity/#Example-continuous-adjoints-on-an-energy-functional

In the documentation it says:
```
function dg(out,u,p,t)
  out[1]= u[1] + u[2]
  out[2]= u[1] + u[2]
end
```
is this a typo? I'd think it would be
```
function dg(out,u,p,t)
  out[1]= u[1] 
  out[2]= u[2]
end
```
If this is not a typo, why is this it?

**Comment by ChrisRackauckas** [comment]
`(u1 + u2)^2 / 2` there's a mixed term.
