### ISSUE TITLE
Does repeat in Ensemble runs start from 1?

### ISSUE THREAD

**Issue by sosiristseng** [SciML/DiffEqDocs.jl#545]
[This page](https://diffeq.sciml.ai/stable/features/ensemble/) about ensemble simulations says:

https://github.com/SciML/DiffEqDocs.jl/blob/c5f5e057def2e361e88dc9a307f098a43565ba88/docs/src/features/ensemble.md?plain=1#L25

However, while I was doing ensemble simulations where `prob_func` depended on the number of repeats, I found that they were always off by one. And it indeed starts from one:

https://github.com/SciML/SciMLBase.jl/blob/0349ed739d0a22951d723e36da7ea7425be8d42a/src/ensemble/basic_ensemble_solve.jl?plain=1#L139

Should the documentation be updated?

**Comment by ChrisRackauckas** [comment]
Yes, the docs should be updated.
