### ISSUE TITLE
Explanation of `DEStats`

### ISSUE THREAD

**Issue by scheidan** [SciML/DiffEqDocs.jl#555]
Solvers return useful statistics in the field `DEStats`, however, their meaning is not explained in the documentation.

The best I could find was this discussion: https://discourse.julialang.org/t/ode-solver-stats/30150

Noting urgent, bit I think it would make a nice little amendment.

**Comment by ChrisRackauckas** [comment]
Thanks yes, I've been adding docstrings to things all week but just haven't gotten to this one yet.
