### ISSUE TITLE
Link to Return Codes is broken in `check_error`

### ISSUE THREAD

**Issue by Datseris** [SciML/DiffEqDocs.jl#567]
The link within this docstring: https://diffeq.sciml.ai/stable/basics/integrator/#SciMLBase.check_error  points to a 404.

**Comment by ChrisRackauckas** [comment]
It should be https://diffeq.sciml.ai/stable/basics/solution/#retcodes. Which docstring?

**Comment by Datseris** [comment]
The one I linked above: 
![image](https://user-images.githubusercontent.com/19669089/179237969-95bceb82-8c5d-4190-bac9-befacca35f71.png)

**Comment by Datseris** [comment]
(cliking Return Codes gives 404)

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/SciMLBase.jl/commit/08766043c1ac630ae74075e16f526d5116497f75
