### ISSUE TITLE
Errors in the examples of dual number errors in the FAQ

### ISSUE THREAD

**Issue by larsmolstad** [SciML/DiffEqDocs.jl#573]
[https://github.com/SciML/DiffEqDocs.jl/blob/master/docs/src/basics/faq.md](url)
For the last examples on the page,
`prob = ODEProblem(f,rand(4),(0.0,1.0))`
`sol = solve(prob,Rosenbrock23(autodiff=false))`,

should the first line be deleted? Using the prob statement from the cell above works:

`prob = ODEProblem(foo, ones(5, 5), (0., 1.0), (ones(5,5), zeros(5,5)))`
`sol = solve(prob,Rosenbrock23(autodiff=false))`

The next example fails because dualcache is not in DiffEqBase (v6.94.4), but in PreallocationTools.

`prob = ODEProblem(foo, ones(5, 5), (0., 1.0), (ones(5,5), DiffEqBase.dualcache(zeros(5,5))))`

should perhaps be

`prob = ODEProblem(foo, ones(5, 5), (0., 1.0), (ones(5,5), PreallocationTools.dualcache(zeros(5,5))))`

or just 

`prob = ODEProblem(foo, ones(5, 5), (0., 1.0), (ones(5,5), dualcache(zeros(5,5))))`.

**Comment by ChrisRackauckas** [comment]
Yes, dualcache moved from DiffEqBase to PreallocationTools.jl, so this needs to get updated.
