### ISSUE TITLE
Sensitivity Analysis points to DiffEqSensitivity

### ISSUE THREAD

**Issue by phipsgabler** [SciML/DiffEqDocs.jl#583]
Basically the same as the root cause of https://github.com/SciML/SciMLSensitivity.jl/issues/733:  the index of https://diffeq.sciml.ai/stable/ links to https://diffeq.sciml.ai/stable/analysis/sensitivity/, which talks about DiffEqSensitivity, not SciMLSensitivity. But using the former leads to weird errors, or segfaults when Enzyme is used.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/SciML/DiffEqDocs.jl/releases/tag/v7.4.0
