### ISSUE TITLE
Ensemble threading for JumpProblem

### ISSUE THREAD

**Issue by lgravina1997** [SciML/DiffEqDocs.jl#586]
Hello, it seems that ensemble threading is not supported for jump problems. Is there any way to get past this?
A minimal example of this would be the following 

![Screenshot 2022-10-07 at 16-22-52 ISSUE - Jupyter Notebook](https://user-images.githubusercontent.com/94217736/194576443-eaa739cd-e164-4848-ad7f-c2025aca8376.png)

**Comment by ChrisRackauckas** [comment]
You just need to give the solver what algorithm to use. `sol = solve(ensembleprob, EnsembleThreads(), Tsit5(), trajectories=600`. That should be it, but I didn't run it. Let me know if there's any issue.

**Comment by lgravina1997** [comment]
Hi thanks for your answer. I tried it but unfortunately  it keeps giving the same problem.

**Comment by lgravina1997** [comment]
The only problem I see now is that because of the jumps ensemble analyzing tools such as `timeseries_steps_mean(sol)` do not work properly. They try to access elements of an array that are not there.
