### ISSUE TITLE
unsupported dynamic function invocation (call to --basic operation--)

### ISSUE THREAD

**Issue by lgravina1997** [SciML/DiffEqDocs.jl#587]
When moving the basic example provided in the tutorial to an ensemble dispach all basic operation if conducted on matrix level give errors. Is there a way to fix this?

A basic example is:

<img width="1134" alt="Screenshot 2022-10-08 at 01 41 35" src="https://user-images.githubusercontent.com/94217736/194675822-278df11d-8fe5-4e1e-abd3-0d793d9d8c0f.png">

**Comment by ChrisRackauckas** [comment]
This doesn't make much sense. The kernel is too big for EnsembleGPUArray to be helpful, and the `f` calls are already on the GPU. I assume you mean EnsembleSerial() here? Closing since this is a usage error, but feel free to continue asking questions.
