### ISSUE TITLE
global search bar is broken 

### ISSUE THREAD

**Issue by anandijain** [SciML/DiffEqDocs.jl#640]
@oscardssmith and i both tried

@ChrisRackauckas i know you said its just that it's a bit laggy, but i've never gotten it to work

https://github.com/JuliaComputing/MultiDocumenter.jl/issues/36 i think this is the relevant issue

**Comment by ChrisRackauckas** [comment]
It was just buggy for me at one point, but indeed I can no longer even get it to be buggy.

**Comment by sethaxen** [comment]
The bar seems to be working now. How did you fix it?

**Comment by ChrisRackauckas** [comment]
A new release of MultiDocumenter https://github.com/JuliaComputing/MultiDocumenter.jl/pull/40
