### ISSUE TITLE
Confusing paragraph in Supporting and Citing section

### ISSUE THREAD

**Issue by DanielVandH** [SciML/DiffEqDocs.jl#648]
Maybe I'm just misreading this for some reason, but in the "Supporting and Citing" section of https://docs.sciml.ai/DiffEqDocs/stable/, there is a sentence after the BibTeX that reads

> is necessary for any use of DifferentialEquations.jl or the packages that are maintained as part of its suite (OrdinaryDiffEq.jl, Sundials.jl, DiffEqDevTools.jl, etc.).

This is the start of a new sentence. I'm assumed this should be a continuation of "we would be grateful if you could cite our work." above. Perhaps the confusing sentence above is meant to be "as necessary for any use of...", and the period removed in "we would be grateful if you could cite our work" to make the continuation clearer.

I also think two capitals are missing in the BibTeX - should it be

>   title={Differential{E}quations.jl--a performant and feature-rich ecosystem for solving differential equations in {J}ulia},

?

**Comment by ChrisRackauckas** [comment]
We would happily accept any grammar improvements, and TeX fixes
