### ISSUE TITLE
Broken references

### ISSUE THREAD

**Issue by DanielVandH** [SciML/DiffEqDocs.jl#649]
The references to IController, PIController, PIDController, and PredictiveController in the "Advanced Adaptive Stepsize Control" section of https://docs.sciml.ai/DiffEqDocs/stable/basics/common_solver_opts/ are broken. I assume it should go to the references as the ones here https://docs.sciml.ai/DiffEqDocs/stable/extras/timestepping/?

The section header  "Advanced Adaptive Stepsize Control" also links to something that is broken.

**Comment by ChrisRackauckas** [comment]
Yes those should point to the docstrings.

@ArnoStrouwen can you help out here?

**Comment by ArnoStrouwen** [comment]
I think they work now on https://docs.sciml.ai/DiffEqDocs/dev/basics/common_solver_opts/.
