### ISSUE TITLE
Formatter passes locally

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/DiffEqDocs.jl#652]
But CI says it does not pass https://github.com/SciML/DiffEqDocs.jl/actions/runs/4183936809/jobs/7248932007

**Comment by ChrisRackauckas** [comment]
Same version?

**Comment by ArnoStrouwen** [comment]
Yes.

**Comment by ArnoStrouwen** [comment]
It was the previous PR that was not formatted properly before it was merged in.
Fixed now in https://github.com/SciML/DiffEqDocs.jl/pull/651.
