### ISSUE TITLE
Link to sensitivity analysis broken in FAQ

### ISSUE THREAD

**Issue by andreasnoack** [SciML/DiffEqDocs.jl#666]
The link https://docs.sciml.ai/DiffEqDocs/stable/basics/faq/basics/@ref%20sensitivity in the section https://docs.sciml.ai/DiffEqDocs/stable/basics/faq/#Autodifferentiation-and-Dual-Numbers currently returns 403

**Comment by ArnoStrouwen** [comment]
I think it is already fixed on dev.
