### ISSUE TITLE
Warning about exceptions for in-place algorithms seems out of date

### ISSUE THREAD

**Issue by moble** [SciML/DiffEqDocs.jl#667]
The FAQ contains these lines:

https://github.com/SciML/DiffEqDocs.jl/blob/a5ae39873c995254763de9f593e4de4046c13176/docs/src/basics/faq.md?plain=1#L187-L188

Following the trail of issues, that looks out of date to me.  Can the parenthetical clause be removed?

**Comment by ChrisRackauckas** [comment]
Thanks indeed this was fixed.
