### ISSUE TITLE
Bug in the "Growing Cell Population" example

### ISSUE THREAD

**Issue by evan-wehi** [SciML/DiffEqDocs.jl#681]
There is a bug in example 3 of the [ContinuousCallback Examples](https://docs.sciml.ai/DiffEqDocs/stable/features/callback_functions/#ContinuousCallback-Examples).

Specificially, the `affect!` function should be
```
function affect!(integrator)
  u = integrator.u
  maxidx = findmax(u)[2]
  resize!(integrator, length(u) + 1)
  Θ = rand()
  u[maxidx] = Θ
  u[end] = 1 - Θ
  nothing
end
```

Lines 2 and 3 are swapped so that determing the location of the maximum value in the state vector is done _before_ the state vector is resized. Doing it after resizing, as the code currently does, means `findmax` can return the wrong index. When this happens the cell that should have divided doesn't and it's value will go over 1, the condition is never met again, and division stops.

**Comment by ChrisRackauckas** [comment]
Thanks! This will be fixed in the next docs build.
