### ISSUE TITLE
Constructor for SplitFunction is incorrect

### ISSUE THREAD

**Issue by DanielVandH** [SciML/DiffEqDocs.jl#688]
The `SplitFunction` constructor documented [here](https://docs.sciml.ai/DiffEqDocs/stable/types/split_ode_types/) doesn't seem to make sense. Should each `f` in the constructor's kwargs be `f1`?

**Comment by ChrisRackauckas** [comment]
yes

**Comment by DanielVandH** [comment]
https://github.com/SciML/SciMLBase.jl/pull/492
