### ISSUE TITLE
Question - and possible suggestion for improvement?

### ISSUE THREAD

**Issue by ignace-computing** [SciML/DiffEqDocs.jl#701]
Hello,

Great package.
How can one see which ODE solvers are supported by `OrdinaryDiffEq.jl `and which aren't?
IMHO, this info might be worth adding somewhere.

Thanks!
Ignace

**Comment by ArnoStrouwen** [comment]
Do you mean like this:
https://docs.sciml.ai/DiffEqDocs/stable/solvers/ode_solve/
There is also the following work in progress:
https://docs.sciml.ai/OrdinaryDiffEq/stable/nonstiff/explicitrk/

**Comment by ignace-computing** [comment]
https://docs.sciml.ai/DiffEqDocs/stable/solvers/ode_solve/ is indeed exactly what I was looking for.
Thank you very much!
The WIP looks great too!

**Comment by ChrisRackauckas** [comment]
Yeah this seems to already exist, so closing unless other concrete asks come.
