### ISSUE TITLE
Are RadauIIA5 and other non-Rosenbrock methods supposed to ignore a broken tGrad?

### ISSUE THREAD

**Issue by novalex98** [SciML/DiffEqDocs.jl#705]
I'm trying to solve a difficult problem, and after explicitly implementing tGrad, I tested it on my usual well defined RadauIIA5 test cases. The test passed, so I submitted a bunch of jobs to a high performance computer. The next morning, I found that Rosenbrock23 failed because of a very simple typo in my tGrad functions. In other words, RadauIIA5, and the other methods I ran, just ignored the tGrad argument they received. Based on this thread https://discourse.julialang.org/t/argument-tgrad-in-odefunction-appears-to-have-no-influence-correct/69236 this might be expected behavior, but I wanted to check.

**Comment by ChrisRackauckas** [comment]
Yes, only Rosenbrock methods use the tgrad function, the other solvers will ignore it.
