### ISSUE TITLE
Out of date docs

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/DiffEqDocs.jl#761]
7.10 is the latest doc release, even though DifferentialEquations is up to 7.14.

**Comment by ChrisRackauckas** [comment]
Yes, this is because the docs don't build because ReverseDiff is showing up in an optimization which should only have ForwardDiff. @Vaibhavdixit02 please let me know when I can rebuild the docs without this error.

**Comment by Vaibhavdixit02** [comment]
I have released OptimizationBase with this fixed

**Comment by ChrisRackauckas** [comment]
Fixed the build and cut the release.
